### PR TITLE
Add mock command

### PR DESCRIPTION
**Pull request by AndroidKitKat**
Feel free to give feedback

### CODE REVIEW

**Comment by colfrog** [comment]
Beautiful mocking algorithm.

What if you went through logs with getLogs(channel, count, callback) ([for example](https://github.com/colfrog/jesi/blob/master/modules/replace.js#L22)) and mocked the last message? You could also take a nick as argument and mock them if they have a message in the last 5 of the logs or something. You should also push the loops that change `text` to a separate function.

Don't mock yourself.

**Comment by AndroidKitKat** [comment]
Can do that no problem. 🥉

**Comment by AndroidKitKat** [comment]
I did it! 🚒

**Comment by colfrog** [comment]
Hurray! Thank you!

**Pull request merged**
